## access array elements

In [3]:
import numpy as np
first=np.array([3,5,6,2,5])
print(first)

[3 5 6 2 5]


In [4]:
print(first[0])

3


In [5]:
print(first[4])

5


In [6]:
print(first[2]+first[3])

8


In [7]:
import numpy as np
first=np.array([[3,5,6,2,5],[4,1,5,3,4]])
print(first)

[[3 5 6 2 5]
 [4 1 5 3 4]]


In [9]:
print(first[1,0])

4


In [10]:
print(first[1,2])

5


In [12]:
print(first[0,-1])

5


## Numpy Array Slicing

In [15]:
import numpy as np 
num=np.array([5,3,6,3,2,5,7,7])
print(num)

[5 3 6 3 2 5 7 7]


In [16]:
print(num[2:])

[6 3 2 5 7 7]


In [17]:
print(num[4:6])

[2 5]


In [18]:
print(num[:5])

[5 3 6 3 2]


## arr[start:stop:step]

In [20]:
import numpy as np 
num=np.array([5,3,6,3,2,5,7,7])
print(num[1:7:3])

[3 2]


In [22]:
print(num[::3])

[5 3 7]


## ".shape" _ Rows and Column

In [32]:
## ".ndim" _ Number of Dimention
## ".size" _ Total number of Elements
## ".dtype"_ DataType

In [28]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([[1,2],[3,4]])
print(arr1)
print(arr2)

[1 2 3]
[[1 2]
 [3 4]]


In [29]:
print(arr2.shape)

(2, 2)


In [30]:
print(arr1.shape)

(3,)
