### Addition add() function sums contents of 2 array

In [2]:
import numpy as np
arr1=np.array([32,56,1,7,543])
arr2=np.array([23,5,12,7,4])
addition=np.add(arr1,arr2)
print(addition)

[ 55  61  13  14 547]


### Subtraction

In [3]:
import numpy as np
arr1=np.array([32,56,1,7,543])
arr2=np.array([23,5,12,7,4])
addition=np.subtract(arr1,arr2)
print(addition)

[  9  51 -11   0 539]


### Multyplication

In [4]:
import numpy as np
arr1=np.array([32,56,1,7,543])
arr2=np.array([23,5,12,7,4])
addition=np.multiply(arr1,arr2)
print(addition)

[ 736  280   12   49 2172]


### Division

In [6]:
import numpy as np
arr1=np.array([32,56,1,7,543])
arr2=np.array([2,5,2,7,4])
addition=np.divide(arr1,arr2)
print(addition)

[ 16.    11.2    0.5    1.   135.75]


### Power

In [7]:
import numpy as np
arr1=np.array([32,56,1,7,543])
arr2=np.array([2,5,2,7,4])
power=np.power(arr1,arr2)
print(power)

[      1024  550731776          1     823543 1036586881]


### Remainder

In [8]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

mode = np.mod(arr1, arr2)

print(mode)

[ 1  6  3  0  0 27]


In [9]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

mode = np.remainder(arr1, arr2)

print(mode)

[ 1  6  3  0  0 27]


### Absolute Values

In [10]:
import numpy as np
arr=np.array([7.47835,-1,-4,-7,0.57])
absolute=np.absolute(arr)
print(absolute)

[7.47835 1.      4.      7.      0.57   ]
