### The Difference Between Copy and View
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [2]:
import numpy as np
arr=np.array([3,5,67,2])
x=arr.copy()
arr[0]=123
print(arr)
print(x)

[123   5  67   2]
[ 3  5 67  2]


In [3]:
import numpy as np
arr=np.array([3,5,67,2])
x=arr.view()
arr[0]=123
print(arr)
print(x)

[123   5  67   2]
[123   5  67   2]


In [4]:
import numpy as np
arr=np.array([3,5,67,2])
x=arr.view()
y=arr.copy()
arr[0]=123
print(arr)
print(x)
print(y)
print(x.base)
print(y.base)

[123   5  67   2]
[123   5  67   2]
[ 3  5 67  2]
[123   5  67   2]
None


### shape of an array

In [7]:
import numpy as np
arr=np.array([[4,5,3,3],[4,2,1,6]])
print(arr)
print(arr.shape)

[[4 5 3 3]
 [4 2 1 6]]
(2, 4)


In [9]:
import numpy as np
x=np.array([4,5,6,2],ndmin=5)
print(x)
print(x.shape)           
           

[[[[[4 5 6 2]]]]]
(1, 1, 1, 1, 4)


## Array Reshaping

In [13]:
import numpy as np
x=np.array([4,5,6,2,6,2,8,9,3,4,4,8])
print(x.reshape(4,3))

[[4 5 6]
 [2 6 2]
 [8 9 3]
 [4 4 8]]


In [15]:
import numpy as np
x=np.array([4,5,6,2,6,2,8,9,3,4,4,8])
print(x.reshape(2,3,2))

[[[4 5]
  [6 2]
  [6 2]]

 [[8 9]
  [3 4]
  [4 8]]]


In [17]:
x=np.array([4,5,6,2,6,2,8,9,3])
print(x.reshape(3,3))

[[4 5 6]
 [2 6 2]
 [8 9 3]]


In [18]:
print(x.reshape(3,3).base)

[4 5 6 2 6 2 8 9 3]


### unknown dimention

In [19]:
print(x.reshape(3,3,-1))

[[[4]
  [5]
  [6]]

 [[2]
  [6]
  [2]]

 [[8]
  [9]
  [3]]]


In [20]:
print(x.reshape(3,3),-2)

[[4 5 6]
 [2 6 2]
 [8 9 3]] -2


### Flattening the arrays
- Flattening array means converting a multidimensional array into a 1D array.

In [21]:
import numpy as np
arr=np.array([[4,5,3,3],[4,2,1,6]])
print(arr)
print(arr.reshape(-1))

[[4 5 3 3]
 [4 2 1 6]]
[4 5 3 3 4 2 1 6]
