- Numpy is a python library which is working with array
- Numpy standard for Numerical Python

In [3]:
import numpy as np
arr= np.array([5,3,7,5])
print(arr)

[5 3 7 5]


- using tuple to cre ate a array


In [4]:
import numpy as np
arr= np.array((5,3,7,5))
print(arr)

[5 3 7 5]


### 0D array

In [6]:
import numpy as np
arr0=np.array(33)
print(arr0)

33


### 1D array

In [7]:
import numpy as np
arr1=np.array([4,5,7])
print(arr1)

[4 5 7]


### 2D Array

In [9]:
import numpy as np
arr1=np.array([[4,5,7],[34,6,2]])
print(arr1)

[[ 4  5  7]
 [34  6  2]]


### 3D array

In [12]:
import numpy as np
arr1=np.array([[4,5,7],[34,6,2],[5,6,3]])
print(arr1)

[[ 4  5  7]
 [34  6  2]
 [ 5  6  3]]


In [13]:
import numpy as np
arr1=np.array([[[4,5,7],[34,6,2]],[[5,6,3],[5,3,2]]])
print(arr1)

[[[ 4  5  7]
  [34  6  2]]

 [[ 5  6  3]
  [ 5  3  2]]]


### Check array dimention

- In Numpy Array "ndim" attribute is used for indicate the dimention of array

In [ ]:
import numpy as np

a=np.array([[[4,5,7],[34,6,2]],[[5,6,3],[5,3,2]]])
b=np.array([[4,5,7],[34,6,2],[5,6,3]])
c=np.array([[4,5,7],[34,6,2]])
d=np.array(34)
a.