### Data Types in NumPy
- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
-M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [1]:
import numpy as np
arr=np.array([2,5,8,3])
print(arr)
print(arr.dtype)

[2 5 8 3]
int32


In [2]:
import numpy as np
arr=np.array(["de","er"])
print(arr)
print(arr.dtype)

['de' 'er']
<U2


## creating array with a defined type

In [3]:
import numpy as np
arr=np.array([2,5,8,3],dtype='S')
print(arr)
print(arr.dtype)

[b'2' b'5' b'8' b'3']
|S1


In [5]:
import numpy as np
arr=np.array([2,5,8,3])
new_arr=arr.astype('f')
print(new_arr)

[2. 5. 8. 3.]


In [6]:
print(new_arr.dtype)

float32


In [7]:
import numpy as np
arr=np.array([0,3,0,5,0,0,0,4,6,7])
new_arr=arr.astype('bool')
print(new_arr)

[False  True False  True False False False  True  True  True]


In [8]:
print(new_arr.dtype)

bool


In [10]:
import numpy as np
arr=np.array([2,5,8,3])
new_arr=arr.astype('i')
print(new_arr)

[2 5 8 3]


In [11]:
import numpy as np
arr=np.array([2,5,8,3])
new_arr=arr.astype('c')
print(new_arr)

[b'2' b'5' b'8' b'3']


In [13]:
import numpy as np
arr=np.array([2,5,8,3])
new_arr=arr.astype('m')
print(new_arr)

[2 5 8 3]
