## create 1D Numpy Array with number from 0 to 9

In [1]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## extract all odd number from a array

In [9]:
import numpy as np
arr=np.array([0 ,1, 2, 3, 4, 5, 6, 7, 8, 9])
odd=arr[arr%2==1]
odd

array([1, 3, 5, 7, 9])

In [10]:
print(odd)

[1 3 5 7 9]


## extract all even number

In [12]:
import numpy as np
arr=np.array([0 ,1, 2, 3, 4, 5, 6, 7, 8, 9])
even=arr[arr%2==0]
print(even)

[0 2 4 6 8]


## reshape array

In [13]:
import numpy as np
first=np.arange(20)
first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
shape=first.reshape(4,5)
print(shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## identity matrix

In [15]:
identity=np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
