### Iterating Arrays


In [2]:
import numpy as np
arr=np.array([4,3,5,6,2,5,4])
for x in arr:
    print(x)

4
3
5
6
2
5
4


In [3]:
import numpy as np
arr=np.array([[4,3,5],[2,5,4]])
for x in arr:
    print(x)

[4 3 5]
[2 5 4]


In [4]:
import numpy as np
arr=np.array([[4,3,5],[2,5,4]])
for x in arr:
    for y in x:
        print(y)

4
3
5
2
5
4


### Joining Numpy Array

In [7]:
import numpy as np
arr1=np.array([4,2,6,4,3,1,9])
arr2=np.array([4,2,5,2,6,8,9])
arr3=np.concatenate((arr1,arr2))
print(arr3)

[4 2 6 4 3 1 9 4 2 5 2 6 8 9]


In [8]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


### Array sort

In [10]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.sort(arr)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [11]:
import numpy as np
arr1=np.array([4,2,6,4,3,1,9])
arr2=np.array([4,2,5,2,6,8,9])
arr3=np.sort(arr1)
arr4=np.sort(arr2)
print(arr3)
print(arr4)

[1 2 3 4 4 6 9]
[2 2 4 5 6 8 9]


### Search Array

In [12]:
import numpy as np
arr1=np.array([4,2,6,4,3,1,9])
arr2=np.array([4,2,5,2,6,8,9])
x=np.where(arr1%2==0)
print(x)

(array([0, 1, 2, 3]),)


In [13]:
print(arr1[x])

[4 2 6 4]


In [14]:
y=np.where(arr2==2)
print(y)

(array([1, 3]),)


In [15]:
print(arr2[y])

[2 2]


In [20]:
import numpy as np
arr1=np.array([4,6,7,2,5,1,9,0])
x=np.sort(arr1)
print(x)

[0 1 2 4 5 6 7 9]


In [25]:
y=np.searchsorted(x,5)
print(y)

4


In [26]:
y=np.searchsorted(x,5,side='right')
print(y)

5
