In [2]:
from numpy import random
x=random.randint(1000)
print(x)


702


In [3]:
x=random.randint(100)
print(x)

24


### Generate Random Float
- The random module's rand() method returns a random float between 0 and 1.

In [4]:
x=random.rand()
print(x)

0.5291098596764529


In [5]:
x=random.randint(100,size=(6))
print(x)

[ 0 11  5 65 43 43]


In [6]:
x=random.randint(100,size=(3,7))
print(x)

[[86 88 46 33 94 33 38]
 [95 72 13 86 30 61 62]
 [72 17 54 37 68 27 90]]


In [7]:
x=random.rand(3,3)
print(x)

[[0.94737619 0.27796768 0.14806086]
 [0.58495096 0.66816449 0.33133777]
 [0.98483416 0.43646296 0.89870595]]


In [8]:
x=random.choice([4,6,2,1,5])
print(x)

6


In [9]:
x=random.choice([4,6,2,1,5],size=(3,5))
print(x)

[[5 5 4 6 1]
 [2 1 4 2 6]
 [2 1 2 4 1]]


### Random Permutations of Elements
- A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

- The NumPy Random module provides two methods for this: shuffle() and permutation().

In [10]:
from numpy import random
import numpy as np
arr=np.array([3,6,2,67,3,9])
random.shuffle(arr)
print(arr)

[67  6  3  3  2  9]


In [11]:
print(random.permutation(arr))

[ 3  9  2 67  6  3]
