In [1]:
import numpy as np

In [2]:
bbq_boxes=np.full((2,3),'bbq')
print(bbq_boxes)

[['bbq' 'bbq' 'bbq']
 ['bbq' 'bbq' 'bbq']]


In [6]:
kids_order=np.random.randint(1,8,(2,3))
print(kids_order)
                             

[[2 7 1]
 [2 2 5]]


In [10]:
surprise_toppings=np.random.rand(2,3)
print(surprise_toppings)

[[0.29166608 0.10326745 0.51988541]
 [0.14317285 0.55886959 0.58780069]]


In [12]:
# create identity matrix
singnature_pizzas= np.identity(4)
print(singnature_pizzas)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
delivery_times=np.arange(0,70,15) #interval
print(delivery_times)

[ 0 15 30 45 60]


In [15]:
cooking_shifts=np.linspace(0,70,5)  # devide 
print(cooking_shifts)

[ 0.  17.5 35.  52.5 70. ]


In [17]:
orders=np.array(['cheese','veg','spicy','bbq'])
print(orders[2])

spicy


In [19]:
print(orders[1:3])

['veg' 'spicy']


In [20]:
orders=np.array([
    ['cheese','veg'],
    ['spicy','bbq']
])

In [21]:
print(orders[0,1])

veg


In [22]:
print(orders[1,0])

spicy


In [24]:
print(orders[:,0])

['cheese' 'spicy']


In [25]:
print(orders[:,1])

['veg' 'bbq']


In [26]:
print(orders[0,:])

['cheese' 'veg']


In [ ]:
orders=np.array([
    ['cheese','veg','veg'],
    ['spicy','bbq','spicy]
])