# NumPy Arrays


In [5]:
import numpy as np

In [7]:
np.__version__

'1.26.4'

In [9]:
my_list=[-1,0,1]
my_list

[-1, 0, 1]

In [11]:
my_array=np.array([my_list])
my_array

array([[-1,  0,  1]])

In [17]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9],[4,5,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [19]:
matrix_one=np. array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [35]:
#using tuple
my_tuple=(-1,0,1)
my_array=np.array(my_tuple)
my_array,type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [37]:
myarray=np.array([3,5,6,"a"])
myarray

array(['3', '5', '6', 'a'], dtype='<U11')

In [39]:
mylist=[3,"a",5,6]
mylist

[3, 'a', 5, 6]